### ISSUE TITLE
alpha channel near white pixels converted as white color

### ISSUE THREAD

**Issue by Rombersoft** [sullerandras/png_to_xnb#5]
I have white png image 192x168 with rounded corners with 4 px radius
I try to convert it to xnb using wine on ubuntu
Result is image without rounded corners (corners are white). When I do inverting colours in order to my white become black that all works good. When I change my white to ARGB (255,250,250,250) that result is white corners instead transparent. Try different options but nothing result

**Comment by Rombersoft** [comment]
![index](https://user-images.githubusercontent.com/19586466/40783238-839ac27c-64ea-11e8-9c81-6f50294309e1.png)

**Comment by sullerandras** [comment]
Hi @Rombersoft . I checked the attached PNG in GIMP and the corners have these pixel values:
Red: 255
Green: 255
Blue: 255
Alpha: 0

While this supposed to be a fully transparent pixel, C# turns it into a white pixel instead. I think C# tries to help here but i found no way to turn it off.
So the easiest way to solve your issue is to clear the RGB channels for those completely transparent pixels in your image.

**Comment by Rombersoft** [comment]
I'm not agreeing with you because attached image was converted excellent by another application which is based on Microsoft library and works only on Windows OS. More over you looked at pixel x=0, y=0 but look at pixel x=1, y=1, it also has r=255, g=255, b=255 but alpha>0. I think your application is not able to work with white channel does not matter what is alpha channel it has. I can not clear rgb channels because it will not be white color

**Comment by sullerandras** [comment]
I use `Bitmap` to read the image file here:
https://github.com/sullerandras/png_to_xnb/blob/master/png_to_xnb/Program.cs#L250
It can be any image format supported by C#, not only PNG, you may try other formats if PNG does not work for you.

But i tried converting your attached image to XNB, then extracted it into PNG again and the result PNG was identical to the original. I used a Mac OS X with `wine` instead of Ubuntu but that shouldn't matter. Here is the XNB file i got in case you want to compare it to yours:
[test.xnb.gz](https://github.com/sullerandras/png_to_xnb/files/2064608/test.xnb.gz)

In general this png_to_xnb converter surely works because that's what i use to create my Terraria texture pack (and obviously almost all Terraria textures are transparent).

**Comment by Rombersoft** [comment]
I used your converted test.xnb file. But edges are white and not transparent

**Comment by Rombersoft** [comment]
Your application work worse than same microsoft application. And it is fact.

**Comment by sullerandras** [comment]
Can you upload the xnb file created with that microsoft application? I want to see the difference.

**Comment by Rombersoft** [comment]
This is uncompressed .xnb
[sistec.zip](https://github.com/sullerandras/png_to_xnb/files/2071071/sistec.zip)

This is microsoft xnb creator
[XNA_formatter.zip](https://github.com/sullerandras/png_to_xnb/files/2071078/XNA_formatter.zip)
Pay attention that microsoft requires a additional library which can be installed some packages for developers

**Comment by Rombersoft** [comment]
Result of your xnb ![png_to_xnb](https://user-images.githubusercontent.com/19586466/40959314-ff7c7792-68a4-11e8-8530-7d2e6300727f.jpg)
 http://joxi.ru/DrlNkGysVVOlY2

Result of microsoft xnb 
![microsoft](https://user-images.githubusercontent.com/19586466/40959325-0ebe8420-68a5-11e8-8347-28ac9b2c1399.jpg)
 http://joxi.ru/D2P4pl7sqqzOO2

**Comment by sullerandras** [comment]
I extracted the PNG from your XNB file and it seems like the microsoft
compressor modified the color values of the transparent pixels!

The first row from left to right looks like this in the original image:
(255,255,255,0),
(255,255,255,0),
(255,255,255,75),
(255,255,255,170),
(255,255,255,244),
(255,255,255,255)

And this is how it looks like in your xnb file:
(0,0,0,0),
(0,0,0,0),
(75,75,75,75),
(170,170,170,170),
(244,244,244,244),
(255,255,255,255)

This is definitely not part of the XNB format specification so i'm not
very keen on changing my little tool. Not to mention that i don't know
why and how the microsoft compressor changes the color values.

**Comment by trigger-segfault** [comment]
I hope I don't sound like an idiot asking this but, isn't Microsoft just applying premultipled alpha to images converted to xnb? It's a simple multiplying the RGB channels by the alpha (as 0.0-1.0). It's not necessarily part of the specification because xnb's are not required to be converted with premultiplied alpha, it's just the default method.

**Comment by sullerandras** [comment]
Thanks @trigger-death. I have no idea. I guess my tool could have support for premultiplied alpha if that's very popular.
Anyone willing to put together a pull request?

**Comment by trigger-segfault** [comment]
Sounds fun. I can probably write one up tomorrow (June 12th) pretty quickly, I've already got plenty of similar code lying around.

If you have no objections, I'll probably set premultiply as the default, as it should be.
